services:
  db:
    image: postgres:16
    container_name: fintech-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: fintech
    ports:
      - "5432:5432"
    volumes:
      - fintech_pg_data:/var/lib/postgresql/data

volumes:
  fintech_pg_data:
